import React, { useState } from 'react';
import MobileView from '../../components/Sidebar/mobileView';
import Header from "../../components/Header/index";
import Footer from "../../components/Footer/index";
import Avatar1 from "../../assets/avatar1.png";
import TestimonialCard from '../../components/Card/testimonialCard';

const data = [{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
}, {
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
}, {
    UserImg: Avatar1,
    UserName: 'Julie Juz',
    UserComment: 'Very useful Notion templates that inspired me to create my own following my needs. Thank you to give that to the world.',
    month: 'oct',
    date: '14',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ángela Sánchez',
    UserComment: 'I started Notion recently, and I have to say that Notionway has helped me start creating my Second Brain, with inspiration and templates. Thank you!',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Mari Ullom',
    UserComment: 'Notionway is an amazing place to find extremely useful and time saving Notion templates. They have definitely saved me tons of time. Highly recommend.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sila Hassan',
    UserComment: 'These templates have proved to be so helpful for my business as well as personal growth. 100% recommended.',
    month: 'oct',
    date: '12',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Sandi Eveleth',
    UserComment: 'I have purchased many products from Notionway and LOVE them ALL! I recommend them to my clients all the time. The customer service and personal attention is also top-notch so... There\'s just no excuse NOT to buy!',
    month: 'oct',
    date: '8',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Andres',
    UserComment: 'Notionway has been quite helpful to me in managing my agency, managing my time, and managing my life. Modest\'s templates saved me hours and I would recommend everyone to have a look at what he has to offer. You won\'t be disappointed.',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Anurag',
    UserComment: 'I’ve used multiple templates and yours have helped out a lot with my finances in many ways, i’ve been better disciplined and know where every penny goes. Thank you !',
    month: 'oct',
    date: '4',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Manthan Ank',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'oct',
    date: '1',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Martín Peralta',
    UserComment: 'There are several notion templates in Notionway, each with a clean and user-friendly appearance',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ana Conti',
    UserComment: 'Incredible templates! Amazing for those wanting to streamline their business processes. 10/10',
    month: 'sep',
    date: '30',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Angel Viera',
    UserComment: 'Awesome product!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'laure lozano',
    UserComment: 'amazing template! I really appreciate your work. Keep it up!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Ruairi Fitzsimmons',
    UserComment: 'I love templates from Notionway! The level of detail they put into their work is fantastic. I can trust that they are well thought out and will just work without long setup processes or crazy workarounds. Whenever I need a new template, Notionway is always my first stop!',
    month: 'sep',
    date: '29',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Jinson',
    UserComment: 'Notionway has helped me find easy and ready-to-go solutions for my team\'s workpace! It\'s a lifesaver.',
    month: 'sep',
    date: '28',
    year: '2022',
},
{
    UserImg: Avatar1,
    UserName: 'Henrique Marino',
    UserComment: 'It is from Twitter I came to know about you and your work. The templates have been very helpful. I was searching for templates everywhere initially, and now I have a one stop solution. And it is your website. Great work buddy. Wish you all the best.',
    month: 'sep',
    date: '28',
    year: '2022',
},
]

function index() {
    const [open, setOpen] = useState(false);
    return (
        <div>
            <Header />
            <MobileView open={open} setopen={setOpen} />
            {!open ? (
                <div>
                    <div className='py-20'>
                        <h1 className='lg:text-[72px] md:text-[60px] text-[40px] md:leading-[80px] leading-10 text-center font-semibold lg:w-8/12 md:w-10/12 m-10/12 flex  m-auto'>Community of +10,000 productivity seekers</h1>
                        <p className='py-10 text-[20px] opacity-70 text-center font-semibold lg:w-8/12 md:w-10/12 m-10/12 flex  m-auto'>Changing people's lives through the use of a tool that we all love - Notion. If you believe we have changed your life, please leave a testimonial.</p>
                        <button className='bg-black text-white px-6 py-3 drop-shadow-sm text-[20px] rounded-md m-auto justify-center flex'>Leave a testimonial</button>
                    </div>
                    <div className='grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-4 px-8 py-20'>
                        {data.map((items, index) => (
                            <li key={index} className="list-none">
                                <TestimonialCard imgsrc={items.UserImg} userName={items.UserName} userComment={items.UserComment} month={items.month} date={items.date} year={items.year} />
                            </li>

                        ))}
                    </div>
                    <Footer />
                </div>) : (<div></div>)}

        </div>
    )
}

export default index
