name: Node.js CI/CD

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Backend Dependencies
      working-directory: .
      run: npm ci

    # - name: Run Backend Tests
    #   working-directory: ./backend
    #   run: npm test

    # - name: Lint Backend
    #   working-directory: .
    #   run: |
    #     npm run lint
    #     npm run format:check

    # - name: Install Frontend Dependencies
    #   working-directory: ./frontend
    #   run: npm ci

    # - name: Build Frontend
    #   working-directory: ./frontend
    #   run: npm run build

    - name: Deploy to Render
      if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main' && !failure()
      uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_DEPLOY_KEY }}
        wait_deploy: true