name: setup node.js 


on: 
  push: 
    branches : [server]
  pull_request:
    branches : [server]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
    - uses: action/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Lint with ESLint and Prettier
      run: |
        npm run lint
        npm run format: check
